package history

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strconv"
	"testing"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/xotec-solutions/xotec-datalayer/src/internal/db"
	"github.com/xotec-solutions/xotec-datalayer/src/internal/db/repository"
	"github.com/xotec-solutions/xotec-datalayer/src/internal/mls"
	"github.com/xotec-solutions/xotec-datalayer/src/internal/testutil"
)

type historyFixture struct {
	StateID        int64
	CountyID       int64
	CityID         int64
	PropertyCoreID int64
	ListingID      string
}

// ensureHistoryTables creates the history tables if they don't exist
// This is needed because the test database may not have the latest migrations
func ensureHistoryTables(t *testing.T, pool *pgxpool.Pool) {
	t.Helper()
	ctx := context.Background()

	// Check if price_history exists
	var priceTable *string
	if err := pool.QueryRow(ctx, "SELECT to_regclass('public.price_history')").Scan(&priceTable); err != nil {
		t.Fatalf("check price_history: %v", err)
	}

	if priceTable == nil {
		// Check if we have CREATE privileges
		var canCreate bool
		if err := pool.QueryRow(ctx, "SELECT has_schema_privilege(current_user, 'public', 'CREATE')").Scan(&canCreate); err != nil {
			t.Fatalf("check CREATE privilege: %v", err)
		}

		if !canCreate {
			t.Skip("missing price_history table; apply migrations or grant CREATE privilege")
		}

		// Create price_history table
		_, err := pool.Exec(ctx, `
			CREATE TABLE IF NOT EXISTS public.price_history
			(
				id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				property_core_id BIGINT         NOT NULL,
				listing_id       VARCHAR(255)   NOT NULL,
				price            NUMERIC(12, 2) NOT NULL,
				previous_price   NUMERIC(12, 2),
				price_type       VARCHAR(25)    NOT NULL,
				change_pct       NUMERIC(8, 4),
				recorded_at      TIMESTAMPTZ    NOT NULL,
				created_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),
				CONSTRAINT price_history_property_core_fk
					FOREIGN KEY (property_core_id) REFERENCES public.properties_core (id) NOT VALID
			);
			CREATE INDEX IF NOT EXISTS price_history_property_core_id_idx ON public.price_history (property_core_id);
			CREATE INDEX IF NOT EXISTS price_history_listing_id_idx ON public.price_history (listing_id);
			CREATE INDEX IF NOT EXISTS price_history_recorded_at_idx ON public.price_history (recorded_at DESC);
			CREATE INDEX IF NOT EXISTS price_history_price_type_idx ON public.price_history (price_type);
		`)
		if err != nil {
			t.Fatalf("create price_history: %v", err)
		}
	}

	// Check if status_history exists
	var statusTable *string
	if err := pool.QueryRow(ctx, "SELECT to_regclass('public.status_history')").Scan(&statusTable); err != nil {
		t.Fatalf("check status_history: %v", err)
	}

	if statusTable == nil {
		// Create status_history table
		_, err := pool.Exec(ctx, `
			CREATE TABLE IF NOT EXISTS public.status_history
			(
				id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				property_core_id BIGINT       NOT NULL,
				listing_id       VARCHAR(255) NOT NULL,
				previous_status  VARCHAR(25),
				new_status       VARCHAR(25)  NOT NULL,
				status_type      VARCHAR(25)  NOT NULL,
				recorded_at      TIMESTAMPTZ  NOT NULL,
				created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
				CONSTRAINT status_history_property_core_fk
					FOREIGN KEY (property_core_id) REFERENCES public.properties_core (id) NOT VALID
			);
			CREATE INDEX IF NOT EXISTS status_history_property_core_id_idx ON public.status_history (property_core_id);
			CREATE INDEX IF NOT EXISTS status_history_listing_id_idx ON public.status_history (listing_id);
			CREATE INDEX IF NOT EXISTS status_history_recorded_at_idx ON public.status_history (recorded_at DESC);
			CREATE INDEX IF NOT EXISTS status_history_status_type_idx ON public.status_history (status_type);
			CREATE INDEX IF NOT EXISTS status_history_new_status_idx ON public.status_history (new_status);
		`)
		if err != nil {
			t.Fatalf("create status_history: %v", err)
		}
	}
}

func seedHistoryFixture(t *testing.T, pool *pgxpool.Pool) historyFixture {
	t.Helper()
	ctx := context.Background()

	// Ensure history tables exist (they may not be in the test database yet)
	ensureHistoryTables(t, pool)

	var fx historyFixture
	suffix := strconv.FormatInt(time.Now().UnixNano(), 10)
	fx.ListingID = "MFRTEST-" + suffix

	// Create state
	err := pool.QueryRow(ctx, `
		INSERT INTO states (name, slug, created_at, updated_at)
		VALUES ($1, $2, NOW(), NOW())
		RETURNING id
	`, "History Test State "+suffix, "history-test-state-"+suffix).Scan(&fx.StateID)
	if err != nil {
		t.Fatalf("insert state: %v", err)
	}

	// Create county
	err = pool.QueryRow(ctx, `
		INSERT INTO counties (state_id, name, slug, created_at, updated_at)
		VALUES ($1, $2, $3, NOW(), NOW())
		RETURNING id
	`, fx.StateID, "History County "+suffix, "history-county-"+suffix).Scan(&fx.CountyID)
	if err != nil {
		t.Fatalf("insert county: %v", err)
	}

	// Create city
	err = pool.QueryRow(ctx, `
		INSERT INTO cities (state_id, county_id, name, normalized_name, slug, created_at, updated_at)
		VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
		RETURNING id
	`, fx.StateID, fx.CountyID, "History City "+suffix, "history city "+suffix, "history-city-"+suffix).Scan(&fx.CityID)
	if err != nil {
		t.Fatalf("insert city: %v", err)
	}

	// Create property_core
	err = pool.QueryRow(ctx, `
		INSERT INTO properties_core (
			listing_id, state_ref_id, city_ref_id,
			standard_status, partition_group, mls_status, list_price,
			previous_list_price, living_area,
			on_market_date, created_at, updated_at
		)
		VALUES ($1, $2, $3, 'Active', 'active', 'Active', 500000,
			475000, 2000,
			CURRENT_DATE - INTERVAL '15 days', NOW(), NOW())
		RETURNING id
	`, fx.ListingID, fx.StateID, fx.CityID).Scan(&fx.PropertyCoreID)
	if err != nil {
		t.Fatalf("insert property_core: %v", err)
	}

	// Insert price history records
	_, err = pool.Exec(ctx, `
		INSERT INTO price_history (property_core_id, listing_id, price, previous_price, price_type, change_pct, recorded_at)
		VALUES 
			($1, $2, 500000, NULL, 'list', NULL, NOW() - INTERVAL '25 days'),
			($1, $2, 525000, 500000, 'list', 5.0, NOW() - INTERVAL '15 days'),
			($1, $2, 510000, 525000, 'list', -2.857, NOW() - INTERVAL '5 days')
	`, fx.PropertyCoreID, fx.ListingID)
	if err != nil {
		t.Fatalf("insert price_history: %v", err)
	}

	// Insert status history records
	_, err = pool.Exec(ctx, `
		INSERT INTO status_history (property_core_id, listing_id, previous_status, new_status, status_type, recorded_at)
		VALUES 
			($1, $2, NULL, 'Active', 'standard', NOW() - INTERVAL '25 days'),
			($1, $2, 'Active', 'Pending', 'standard', NOW() - INTERVAL '10 days'),
			($1, $2, 'Pending', 'Active', 'standard', NOW() - INTERVAL '5 days')
	`, fx.PropertyCoreID, fx.ListingID)
	if err != nil {
		t.Fatalf("insert status_history: %v", err)
	}

	t.Cleanup(func() {
		_, _ = pool.Exec(ctx, "DELETE FROM price_history WHERE listing_id = $1", fx.ListingID)
		_, _ = pool.Exec(ctx, "DELETE FROM status_history WHERE listing_id = $1", fx.ListingID)
		_, _ = pool.Exec(ctx, "DELETE FROM properties_core WHERE listing_id = $1", fx.ListingID)
		_, _ = pool.Exec(ctx, "DELETE FROM cities WHERE id = $1", fx.CityID)
		_, _ = pool.Exec(ctx, "DELETE FROM counties WHERE id = $1", fx.CountyID)
		_, _ = pool.Exec(ctx, "DELETE FROM states WHERE id = $1", fx.StateID)
	})

	return fx
}

func newHistoryHandler(t *testing.T) (*Handler, historyFixture) {
	t.Helper()
	pool := testutil.NewPool(t)
	fx := seedHistoryFixture(t, pool)
	return NewHandler(pool, db.NewRegistry()), fx
}

func decodeJSON(t *testing.T, w *httptest.ResponseRecorder, v any) {
	t.Helper()
	if err := json.NewDecoder(w.Body).Decode(v); err != nil {
		t.Fatalf("decode response: %v", err)
	}
}

// =============================================================================
// Price History Tests
// =============================================================================

func TestGetPriceHistoryByListing_Success(t *testing.T) {
	handler, fx := newHistoryHandler(t)
	r := chi.NewRouter()
	r.Get("/api/v1/history/listing/{listing_id}/prices", handler.GetPriceHistoryByListing)

	bareID := mls.StripPrefix(fx.ListingID)
	req := httptest.NewRequest(http.MethodGet, "/api/v1/history/listing/"+bareID+"/prices", nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", w.Code, w.Body.String())
	}

	var resp priceHistoryResponse
	decodeJSON(t, w, &resp)

	if resp.ListingID != bareID {
		t.Errorf("expected listing_id %s, got %s", bareID, resp.ListingID)
	}
	if len(resp.Records) != 3 {
		t.Errorf("expected 3 records, got %d", len(resp.Records))
	}
}

func TestGetPriceHistoryByListing_NotFound(t *testing.T) {
	handler, _ := newHistoryHandler(t)
	r := chi.NewRouter()
	r.Get("/api/v1/history/listing/{listing_id}/prices", handler.GetPriceHistoryByListing)

	req := httptest.NewRequest(http.MethodGet, "/api/v1/history/listing/NONEXISTENT-123/prices", nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d", w.Code)
	}

	var resp priceHistoryResponse
	decodeJSON(t, w, &resp)

	if len(resp.Records) != 0 {
		t.Errorf("expected 0 records, got %d", len(resp.Records))
	}
}

// =============================================================================
// Status History Tests
// =============================================================================

func TestGetStatusHistoryByListing_Success(t *testing.T) {
	handler, fx := newHistoryHandler(t)
	r := chi.NewRouter()
	r.Get("/api/v1/history/listing/{listing_id}/status", handler.GetStatusHistoryByListing)

	bareID := mls.StripPrefix(fx.ListingID)
	req := httptest.NewRequest(http.MethodGet, "/api/v1/history/listing/"+bareID+"/status", nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", w.Code, w.Body.String())
	}

	var resp statusHistoryResponse
	decodeJSON(t, w, &resp)

	if resp.ListingID != bareID {
		t.Errorf("expected listing_id %s, got %s", bareID, resp.ListingID)
	}
	if len(resp.Records) != 3 {
		t.Errorf("expected 3 records, got %d", len(resp.Records))
	}
}

// =============================================================================
// Timeline Tests
// =============================================================================

func TestGetListingTimeline_Success(t *testing.T) {
	handler, fx := newHistoryHandler(t)
	r := chi.NewRouter()
	r.Get("/api/v1/history/listing/{listing_id}/timeline", handler.GetListingTimeline)

	bareID := mls.StripPrefix(fx.ListingID)
	req := httptest.NewRequest(http.MethodGet, "/api/v1/history/listing/"+bareID+"/timeline", nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", w.Code, w.Body.String())
	}

	var resp listingTimelineResponse
	decodeJSON(t, w, &resp)

	if resp.ListingID != bareID {
		t.Errorf("expected listing_id %s, got %s", bareID, resp.ListingID)
	}
	// 3 price + 3 status = 6 events
	if len(resp.Events) != 6 {
		t.Errorf("expected 6 events, got %d", len(resp.Events))
	}

	// Verify we have both price and status events
	hasPriceEvent := false
	hasStatusEvent := false
	for _, e := range resp.Events {
		if e.EventType == "price" {
			hasPriceEvent = true
		}
		if e.EventType == "status" {
			hasStatusEvent = true
		}
	}
	if !hasPriceEvent {
		t.Error("expected price event in timeline")
	}
	if !hasStatusEvent {
		t.Error("expected status event in timeline")
	}
}

// =============================================================================
// Geo Trend Tests
// =============================================================================

func TestGetPriceTrends_Success(t *testing.T) {
	handler, fx := newHistoryHandler(t)
	r := chi.NewRouter()
	r.Get("/api/v1/history/trends/prices", handler.GetPriceTrends)

	url := "/api/v1/history/trends/prices?geo_type=state&geo_id=" + strconv.FormatInt(fx.StateID, 10) +
		"&start_date=" + time.Now().AddDate(0, 0, -30).Format("2006-01-02") +
		"&end_date=" + time.Now().Format("2006-01-02") +
		"&interval=week"
	req := httptest.NewRequest(http.MethodGet, url, nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", w.Code, w.Body.String())
	}

	var resp priceTrendsResponse
	decodeJSON(t, w, &resp)

	if resp.GeoType != "state" {
		t.Errorf("expected geo_type state, got %s", resp.GeoType)
	}
	if resp.GeoID != fx.StateID {
		t.Errorf("expected geo_id %d, got %d", fx.StateID, resp.GeoID)
	}
	if resp.Interval != "week" {
		t.Errorf("expected interval week, got %s", resp.Interval)
	}
}

func TestGetPriceTrends_MissingGeoID(t *testing.T) {
	handler, _ := newHistoryHandler(t)
	r := chi.NewRouter()
	r.Get("/api/v1/history/trends/prices", handler.GetPriceTrends)

	req := httptest.NewRequest(http.MethodGet, "/api/v1/history/trends/prices?geo_type=state", nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusBadRequest {
		t.Fatalf("expected 400, got %d", w.Code)
	}
}

func TestGetPriceTrends_InvalidGeoType(t *testing.T) {
	handler, _ := newHistoryHandler(t)
	r := chi.NewRouter()
	r.Get("/api/v1/history/trends/prices", handler.GetPriceTrends)

	req := httptest.NewRequest(http.MethodGet, "/api/v1/history/trends/prices?geo_type=invalid&geo_id=1", nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusBadRequest {
		t.Fatalf("expected 400, got %d", w.Code)
	}
}

func TestGetPriceTrends_InvalidDateFormat(t *testing.T) {
	handler, _ := newHistoryHandler(t)
	r := chi.NewRouter()
	r.Get("/api/v1/history/trends/prices", handler.GetPriceTrends)

	req := httptest.NewRequest(http.MethodGet, "/api/v1/history/trends/prices?geo_type=state&geo_id=1&start_date=bad-date", nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusBadRequest {
		t.Fatalf("expected 400, got %d", w.Code)
	}
}

func TestGetPriceTrends_InvalidInterval(t *testing.T) {
	handler, _ := newHistoryHandler(t)
	r := chi.NewRouter()
	r.Get("/api/v1/history/trends/prices", handler.GetPriceTrends)

	req := httptest.NewRequest(http.MethodGet, "/api/v1/history/trends/prices?geo_type=state&geo_id=1&interval=hourly", nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusBadRequest {
		t.Fatalf("expected 400, got %d", w.Code)
	}
}

func TestGetPriceTrends_DefaultParams(t *testing.T) {
	handler, fx := newHistoryHandler(t)
	r := chi.NewRouter()
	r.Get("/api/v1/history/trends/prices", handler.GetPriceTrends)

	// Only provide geo_id, let others default
	url := "/api/v1/history/trends/prices?geo_id=" + strconv.FormatInt(fx.StateID, 10)
	req := httptest.NewRequest(http.MethodGet, url, nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", w.Code, w.Body.String())
	}

	var resp priceTrendsResponse
	decodeJSON(t, w, &resp)

	// Should use defaults
	if resp.GeoType != "state" {
		t.Errorf("expected default geo_type state, got %s", resp.GeoType)
	}
	if resp.Interval != "day" {
		t.Errorf("expected default interval day, got %s", resp.Interval)
	}
}

func TestGetSalesTrends_Success(t *testing.T) {
	handler, fx := newHistoryHandler(t)
	r := chi.NewRouter()
	r.Get("/api/v1/history/trends/sales", handler.GetSalesTrends)

	url := "/api/v1/history/trends/sales?geo_type=city&geo_id=" + strconv.FormatInt(fx.CityID, 10)
	req := httptest.NewRequest(http.MethodGet, url, nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", w.Code, w.Body.String())
	}

	var resp salesTrendsResponse
	decodeJSON(t, w, &resp)

	if resp.GeoType != "city" {
		t.Errorf("expected geo_type city, got %s", resp.GeoType)
	}
}

func TestGetStatusTransitions_Success(t *testing.T) {
	handler, fx := newHistoryHandler(t)
	r := chi.NewRouter()
	r.Get("/api/v1/history/trends/status", handler.GetStatusTransitions)

	url := "/api/v1/history/trends/status?geo_type=state&geo_id=" + strconv.FormatInt(fx.StateID, 10)
	req := httptest.NewRequest(http.MethodGet, url, nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", w.Code, w.Body.String())
	}

	var resp statusTransitionsResponse
	decodeJSON(t, w, &resp)

	if resp.GeoType != "state" {
		t.Errorf("expected geo_type state, got %s", resp.GeoType)
	}
}

func TestGetNewListingCounts_Success(t *testing.T) {
	handler, fx := newHistoryHandler(t)
	r := chi.NewRouter()
	r.Get("/api/v1/history/trends/listings", handler.GetNewListingCounts)

	url := "/api/v1/history/trends/listings?geo_type=state&geo_id=" + strconv.FormatInt(fx.StateID, 10)
	req := httptest.NewRequest(http.MethodGet, url, nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", w.Code, w.Body.String())
	}

	var resp listingCountsResponse
	decodeJSON(t, w, &resp)

	if resp.GeoType != "state" {
		t.Errorf("expected geo_type state, got %s", resp.GeoType)
	}
}

func TestGetDaysOnMarketTrends_Success(t *testing.T) {
	handler, fx := newHistoryHandler(t)
	r := chi.NewRouter()
	r.Get("/api/v1/history/trends/dom", handler.GetDaysOnMarketTrends)

	url := "/api/v1/history/trends/dom?geo_type=state&geo_id=" + strconv.FormatInt(fx.StateID, 10)
	req := httptest.NewRequest(http.MethodGet, url, nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", w.Code, w.Body.String())
	}

	var resp domTrendsResponse
	decodeJSON(t, w, &resp)

	if resp.GeoType != "state" {
		t.Errorf("expected geo_type state, got %s", resp.GeoType)
	}
}

// =============================================================================
// Stats Tests
// =============================================================================

func TestGetHistoryStats_Success(t *testing.T) {
	handler, _ := newHistoryHandler(t)
	r := chi.NewRouter()
	r.Get("/api/v1/history/stats", handler.GetHistoryStats)

	req := httptest.NewRequest(http.MethodGet, "/api/v1/history/stats", nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", w.Code, w.Body.String())
	}

	var resp historyStatsResponse
	decodeJSON(t, w, &resp)

	// Should have records from fixture
	if resp.Stats.TotalPriceRecords < 3 {
		t.Errorf("expected at least 3 price records, got %d", resp.Stats.TotalPriceRecords)
	}
	if resp.Stats.TotalStatusRecords < 3 {
		t.Errorf("expected at least 3 status records, got %d", resp.Stats.TotalStatusRecords)
	}
}

// =============================================================================
// Price Change Summary Tests
// =============================================================================

func TestGetPriceChangeSummary_Success(t *testing.T) {
	handler, fx := newHistoryHandler(t)
	r := chi.NewRouter()
	r.Get("/api/v1/history/summary/prices", handler.GetPriceChangeSummary)

	url := "/api/v1/history/summary/prices?geo_type=state&geo_id=" + strconv.FormatInt(fx.StateID, 10)
	req := httptest.NewRequest(http.MethodGet, url, nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", w.Code, w.Body.String())
	}

	var resp priceChangeSummaryResponse
	decodeJSON(t, w, &resp)

	if resp.GeoType != "state" {
		t.Errorf("expected geo_type state, got %s", resp.GeoType)
	}
}

// =============================================================================
// Repository Function Tests
// =============================================================================

func TestInsertPriceHistory(t *testing.T) {
	pool := testutil.NewPool(t)
	ctx := context.Background()

	// Ensure history tables exist
	ensureHistoryTables(t, pool)

	suffix := strconv.FormatInt(time.Now().UnixNano(), 10)
	listingID := "PRICE-" + suffix

	// Create state, county, city, property_core
	var stateID, countyID, cityID, propertyID int64
	err := pool.QueryRow(ctx, `
		INSERT INTO states (name, slug, created_at, updated_at)
		VALUES ($1, $2, NOW(), NOW())
		RETURNING id
	`, "Price State "+suffix, "price-state-"+suffix).Scan(&stateID)
	if err != nil {
		t.Fatalf("insert state: %v", err)
	}

	err = pool.QueryRow(ctx, `
		INSERT INTO counties (state_id, name, slug, created_at, updated_at)
		VALUES ($1, $2, $3, NOW(), NOW())
		RETURNING id
	`, stateID, "Price County "+suffix, "price-county-"+suffix).Scan(&countyID)
	if err != nil {
		t.Fatalf("insert county: %v", err)
	}

	err = pool.QueryRow(ctx, `
		INSERT INTO cities (state_id, county_id, name, normalized_name, slug, created_at, updated_at)
		VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
		RETURNING id
	`, stateID, countyID, "Price City "+suffix, "price city "+suffix, "price-city-"+suffix).Scan(&cityID)
	if err != nil {
		t.Fatalf("insert city: %v", err)
	}

	err = pool.QueryRow(ctx, `
		INSERT INTO properties_core (listing_id, state_ref_id, city_ref_id, standard_status, partition_group, list_price, created_at, updated_at)
		VALUES ($1, $2, $3, 'Active', 'active', 500000, NOW(), NOW())
		RETURNING id
	`, listingID, stateID, cityID).Scan(&propertyID)
	if err != nil {
		t.Fatalf("insert property_core: %v", err)
	}

	t.Cleanup(func() {
		_, _ = pool.Exec(ctx, "DELETE FROM price_history WHERE listing_id = $1", listingID)
		_, _ = pool.Exec(ctx, "DELETE FROM properties_core WHERE listing_id = $1", listingID)
		_, _ = pool.Exec(ctx, "DELETE FROM cities WHERE id = $1", cityID)
		_, _ = pool.Exec(ctx, "DELETE FROM counties WHERE id = $1", countyID)
		_, _ = pool.Exec(ctx, "DELETE FROM states WHERE id = $1", stateID)
	})

	// Insert price history
	prevPrice := 450000.0
	changePct := 11.11
	record := repository.PriceHistoryRecord{
		PropertyCoreID: propertyID,
		ListingID:      listingID,
		Price:          500000,
		PreviousPrice:  &prevPrice,
		PriceType:      "list",
		ChangePct:      &changePct,
		RecordedAt:     time.Now(),
	}

	err = repository.InsertPriceHistory(ctx, pool, record)
	if err != nil {
		t.Fatalf("insert price history: %v", err)
	}

	// Verify
	records, err := repository.GetPriceHistoryByListing(ctx, pool, listingID)
	if err != nil {
		t.Fatalf("get price history: %v", err)
	}
	if len(records) != 1 {
		t.Fatalf("expected 1 record, got %d", len(records))
	}
	if records[0].Price != 500000 {
		t.Errorf("expected price 500000, got %f", records[0].Price)
	}
	if records[0].PriceType != "list" {
		t.Errorf("expected price_type list, got %s", records[0].PriceType)
	}
}

func TestInsertStatusHistory(t *testing.T) {
	pool := testutil.NewPool(t)
	ctx := context.Background()

	// Ensure history tables exist
	ensureHistoryTables(t, pool)

	suffix := strconv.FormatInt(time.Now().UnixNano(), 10)
	listingID := "STATUS-" + suffix

	// Create state, county, city, property_core
	var stateID, countyID, cityID, propertyID int64
	err := pool.QueryRow(ctx, `
		INSERT INTO states (name, slug, created_at, updated_at)
		VALUES ($1, $2, NOW(), NOW())
		RETURNING id
	`, "Status State "+suffix, "status-state-"+suffix).Scan(&stateID)
	if err != nil {
		t.Fatalf("insert state: %v", err)
	}

	err = pool.QueryRow(ctx, `
		INSERT INTO counties (state_id, name, slug, created_at, updated_at)
		VALUES ($1, $2, $3, NOW(), NOW())
		RETURNING id
	`, stateID, "Status County "+suffix, "status-county-"+suffix).Scan(&countyID)
	if err != nil {
		t.Fatalf("insert county: %v", err)
	}

	err = pool.QueryRow(ctx, `
		INSERT INTO cities (state_id, county_id, name, normalized_name, slug, created_at, updated_at)
		VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
		RETURNING id
	`, stateID, countyID, "Status City "+suffix, "status city "+suffix, "status-city-"+suffix).Scan(&cityID)
	if err != nil {
		t.Fatalf("insert city: %v", err)
	}

	err = pool.QueryRow(ctx, `
		INSERT INTO properties_core (listing_id, state_ref_id, city_ref_id, standard_status, partition_group, created_at, updated_at)
		VALUES ($1, $2, $3, 'Active', 'active', NOW(), NOW())
		RETURNING id
	`, listingID, stateID, cityID).Scan(&propertyID)
	if err != nil {
		t.Fatalf("insert property_core: %v", err)
	}

	t.Cleanup(func() {
		_, _ = pool.Exec(ctx, "DELETE FROM status_history WHERE listing_id = $1", listingID)
		_, _ = pool.Exec(ctx, "DELETE FROM properties_core WHERE listing_id = $1", listingID)
		_, _ = pool.Exec(ctx, "DELETE FROM cities WHERE id = $1", cityID)
		_, _ = pool.Exec(ctx, "DELETE FROM counties WHERE id = $1", countyID)
		_, _ = pool.Exec(ctx, "DELETE FROM states WHERE id = $1", stateID)
	})

	// Insert status history
	prevStatus := "Active"
	record := repository.StatusHistoryRecord{
		PropertyCoreID: propertyID,
		ListingID:      listingID,
		PreviousStatus: &prevStatus,
		NewStatus:      "Pending",
		StatusType:     "standard",
		RecordedAt:     time.Now(),
	}

	err = repository.InsertStatusHistory(ctx, pool, record)
	if err != nil {
		t.Fatalf("insert status history: %v", err)
	}

	// Verify
	records, err := repository.GetStatusHistoryByListing(ctx, pool, listingID)
	if err != nil {
		t.Fatalf("get status history: %v", err)
	}
	if len(records) != 1 {
		t.Fatalf("expected 1 record, got %d", len(records))
	}
	if records[0].NewStatus != "Pending" {
		t.Errorf("expected new_status Pending, got %s", records[0].NewStatus)
	}
	if records[0].StatusType != "standard" {
		t.Errorf("expected status_type standard, got %s", records[0].StatusType)
	}
}

func TestDeleteOldHistory(t *testing.T) {
	pool := testutil.NewPool(t)
	ctx := context.Background()

	// Ensure history tables exist
	ensureHistoryTables(t, pool)

	suffix := strconv.FormatInt(time.Now().UnixNano(), 10)
	listingID := "DEL-" + suffix

	// Create state, county, city, property_core
	var stateID, countyID, cityID, propertyID int64
	err := pool.QueryRow(ctx, `
		INSERT INTO states (name, slug, created_at, updated_at)
		VALUES ($1, $2, NOW(), NOW())
		RETURNING id
	`, "Delete State "+suffix, "delete-state-"+suffix).Scan(&stateID)
	if err != nil {
		t.Fatalf("insert state: %v", err)
	}

	err = pool.QueryRow(ctx, `
		INSERT INTO counties (state_id, name, slug, created_at, updated_at)
		VALUES ($1, $2, $3, NOW(), NOW())
		RETURNING id
	`, stateID, "Delete County "+suffix, "delete-county-"+suffix).Scan(&countyID)
	if err != nil {
		t.Fatalf("insert county: %v", err)
	}

	err = pool.QueryRow(ctx, `
		INSERT INTO cities (state_id, county_id, name, normalized_name, slug, created_at, updated_at)
		VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
		RETURNING id
	`, stateID, countyID, "Delete City "+suffix, "delete city "+suffix, "delete-city-"+suffix).Scan(&cityID)
	if err != nil {
		t.Fatalf("insert city: %v", err)
	}

	err = pool.QueryRow(ctx, `
		INSERT INTO properties_core (listing_id, state_ref_id, city_ref_id, standard_status, partition_group, created_at, updated_at)
		VALUES ($1, $2, $3, 'Active', 'active', NOW(), NOW())
		RETURNING id
	`, listingID, stateID, cityID).Scan(&propertyID)
	if err != nil {
		t.Fatalf("insert property_core: %v", err)
	}

	// Insert old price history (6 years ago)
	oldDate := time.Now().AddDate(-6, 0, 0)
	_, err = pool.Exec(ctx, `
		INSERT INTO price_history (property_core_id, listing_id, price, price_type, recorded_at)
		VALUES ($1, $2, 400000, 'list', $3)
	`, propertyID, listingID, oldDate)
	if err != nil {
		t.Fatalf("insert old price_history: %v", err)
	}

	// Insert old status history (6 years ago)
	_, err = pool.Exec(ctx, `
		INSERT INTO status_history (property_core_id, listing_id, new_status, status_type, recorded_at)
		VALUES ($1, $2, 'Active', 'standard', $3)
	`, propertyID, listingID, oldDate)
	if err != nil {
		t.Fatalf("insert old status_history: %v", err)
	}

	t.Cleanup(func() {
		_, _ = pool.Exec(ctx, "DELETE FROM price_history WHERE listing_id = $1", listingID)
		_, _ = pool.Exec(ctx, "DELETE FROM status_history WHERE listing_id = $1", listingID)
		_, _ = pool.Exec(ctx, "DELETE FROM properties_core WHERE listing_id = $1", listingID)
		_, _ = pool.Exec(ctx, "DELETE FROM cities WHERE id = $1", cityID)
		_, _ = pool.Exec(ctx, "DELETE FROM counties WHERE id = $1", countyID)
		_, _ = pool.Exec(ctx, "DELETE FROM states WHERE id = $1", stateID)
	})

	// Delete records older than 3 years
	cutoff := time.Now().AddDate(-3, 0, 0)

	priceDeleted, err := repository.DeleteOldPriceHistory(ctx, pool, cutoff)
	if err != nil {
		t.Fatalf("delete old price history: %v", err)
	}
	if priceDeleted < 1 {
		t.Errorf("expected at least 1 price record deleted, got %d", priceDeleted)
	}

	statusDeleted, err := repository.DeleteOldStatusHistory(ctx, pool, cutoff)
	if err != nil {
		t.Fatalf("delete old status history: %v", err)
	}
	if statusDeleted < 1 {
		t.Errorf("expected at least 1 status record deleted, got %d", statusDeleted)
	}
}

// =============================================================================
// Parse Geo Trend Params Tests
// =============================================================================

func TestParseGeoTrendParams_AllParams(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet,
		"/test?geo_type=city&geo_id=123&start_date=2024-01-01&end_date=2024-12-31&interval=month", nil)

	params, err := parseGeoTrendParams(req)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if params.GeoType != "city" {
		t.Errorf("expected geo_type city, got %s", params.GeoType)
	}
	if params.GeoID != 123 {
		t.Errorf("expected geo_id 123, got %d", params.GeoID)
	}
	if params.Interval != "month" {
		t.Errorf("expected interval month, got %s", params.Interval)
	}
	expectedStart := time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC)
	if !params.StartDate.Equal(expectedStart) {
		t.Errorf("expected start_date %v, got %v", expectedStart, params.StartDate)
	}
}

func TestParseGeoTrendParams_InvalidGeoID(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/test?geo_type=city&geo_id=invalid", nil)

	_, err := parseGeoTrendParams(req)
	if err == nil {
		t.Fatal("expected error for invalid geo_id")
	}
}

func TestParseGeoTrendParams_Subdivision(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet,
		"/test?geo_type=subdivision&geo_id=456&interval=month", nil)

	params, err := parseGeoTrendParams(req)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if params.GeoType != "subdivision" {
		t.Errorf("expected geo_type subdivision, got %s", params.GeoType)
	}
}

// =============================================================================
// Market Snapshot Tests
// =============================================================================

func TestGetMarketSnapshot_Success(t *testing.T) {
	handler, fx := newHistoryHandler(t)
	r := chi.NewRouter()
	r.Get("/api/v1/market/snapshot", handler.GetMarketSnapshot)

	url := "/api/v1/market/snapshot?geo_type=city&geo_id=" + strconv.FormatInt(fx.CityID, 10)
	req := httptest.NewRequest(http.MethodGet, url, nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", w.Code, w.Body.String())
	}

	var resp marketSnapshotResponse
	decodeJSON(t, w, &resp)

	if resp.GeoType != "city" {
		t.Errorf("expected geo_type city, got %s", resp.GeoType)
	}
	if resp.GeoID != fx.CityID {
		t.Errorf("expected geo_id %d, got %d", fx.CityID, resp.GeoID)
	}
	if resp.Snapshot.ActiveCount < 1 {
		t.Errorf("expected at least 1 active, got %d", resp.Snapshot.ActiveCount)
	}
	if resp.Snapshot.NewListedCount < 1 {
		t.Errorf("expected at least 1 new listed, got %d", resp.Snapshot.NewListedCount)
	}
}

func TestGetMarketSnapshot_MissingGeoType(t *testing.T) {
	handler, _ := newHistoryHandler(t)
	r := chi.NewRouter()
	r.Get("/api/v1/market/snapshot", handler.GetMarketSnapshot)

	req := httptest.NewRequest(http.MethodGet, "/api/v1/market/snapshot?geo_id=1", nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusBadRequest {
		t.Fatalf("expected 400, got %d", w.Code)
	}
}

func TestGetMarketSnapshot_MissingGeoID(t *testing.T) {
	handler, _ := newHistoryHandler(t)
	r := chi.NewRouter()
	r.Get("/api/v1/market/snapshot", handler.GetMarketSnapshot)

	req := httptest.NewRequest(http.MethodGet, "/api/v1/market/snapshot?geo_type=city", nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusBadRequest {
		t.Fatalf("expected 400, got %d", w.Code)
	}
}

func TestGetMarketSnapshot_WithFilters(t *testing.T) {
	handler, fx := newHistoryHandler(t)
	r := chi.NewRouter()
	r.Get("/api/v1/market/snapshot", handler.GetMarketSnapshot)

	url := "/api/v1/market/snapshot?geo_type=state&geo_id=" + strconv.FormatInt(fx.StateID, 10) +
		"&property_type=Residential"
	req := httptest.NewRequest(http.MethodGet, url, nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", w.Code, w.Body.String())
	}

	var resp marketSnapshotResponse
	decodeJSON(t, w, &resp)

	if resp.Filters.PropertyType == nil || *resp.Filters.PropertyType != "Residential" {
		t.Error("expected property_type filter to be Residential")
	}
}

func TestGetMarketSnapshot_InvalidGeoType(t *testing.T) {
	handler, _ := newHistoryHandler(t)
	r := chi.NewRouter()
	r.Get("/api/v1/market/snapshot", handler.GetMarketSnapshot)

	req := httptest.NewRequest(http.MethodGet, "/api/v1/market/snapshot?geo_type=invalid&geo_id=1", nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusBadRequest {
		t.Fatalf("expected 400, got %d", w.Code)
	}
}
